config/routes.rb
Rails.application.routes.draw do

  resources :accounts, only: [:show, :update, :new, :create] do
    member do
      post :sold_at
    end
  end
  resources :operations, only: [:create, :destroy, :edit, :update]

  root to: 'welcome#index'
end

app/models/account.rb
# == Schema Information
#
# Table name: accounts
#
#  id          :integer          not null, primary key
#  name        :string(255)
#  description :string(255)
#  sold        :float
#  sold_date   :datetime
#  created_at  :datetime
#  updated_at  :datetime
#

class Account < ActiveRecord::Base
  validates :name, presence: true

  has_many :operations
  has_many :incomes, -> { where('amount >= 0') }, class_name: 'Operation'
  has_many :outcomes, -> { where('amount < 0') }, class_name: 'Operation'
  has_many :simulated_account_operations

  def fold_simulated_operations_until(to_date)
    simulated_account_operations.delete_all
    # start_date = Date.parse(Figaro.env.application_start_date)
    (sold_date.to_date..to_date.to_date).each do |day|
      puts "Processing day: #{day}"
      operations.each do |operation|
        if operation.is_on_day?(day)
          simulated_account_operations.create!(operation.to_simulated_account_operation(day))
        end
      end
    end
    simulated_account_operations
  end

  def sold_at(date)
    raise 'Given date was lower than or equal to last sold date' if date <= sold_date
    fold_simulated_operations_until(date)
    sold + simulated_account_operations.map(&:amount).inject(:+)
  end

  def incomes_amount(frequency = nil)
    sum_operations('incomes', frequency)
  end

  def outcomes_amount(frequency = nil)
    sum_operations('outcomes', frequency)
  end

  def sum_operations(type = nil, frequency = nil)
    filtered = (type == 'incomes' ? incomes : outcomes)
    filtered = filtered.where(frequency: frequency) if frequency
    filtered.map(&:amount).inject(:+)
  end
end

app/models/operation.rb
# == Schema Information
#
# Table name: operations
#
#  id           :integer          not null, primary key
#  name         :string(255)
#  description  :string(255)
#  amount       :float
#  date         :datetime
#  date_from    :datetime
#  date_to      :datetime
#  is_recurrent :boolean          default(FALSE)
#  frequency    :string(255)
#  account_id   :integer
#  created_at   :datetime
#  updated_at   :datetime
#

class Operation < ActiveRecord::Base
  FREQUENCIES = %w[punctual daily weekly monthly yearly]

  belongs_to :account

  validates :name, presence: true
  validates :date, presence: true
  validates :amount, presence: true

  before_save :pad_date_to_month

  def pad_date_to_month
    self.date = date.change(day: 28) if date.day > 28
  end

  def to_simulated_account_operation(operation_date = nil)
    { amount: amount, date: operation_date || date, operation_id: id }
  end

  def is_income?
    amount >= 0
  end

  def is_outcome?
    amount < 0
  end

  def is_on_day?(day)
    day.to_date == self.date.to_date || matches_recurring_date?(day)
  end

  def matches_recurring_date?(day)
    return false if date_from && date_to && !(date_from..date_to).include?(day)
    case frequency
    when 'daily'
      true
    when 'weekly'
      day.wday == date.wday
    when 'monthly'
      day.mday == date.mday
    when 'yearly'
      day.yday == date.yday
    else
      false
    end
  end
end

app/models/simulated_account_operation.rb
# == Schema Information
#
# Table name: simulated_account_operations
#
#  id           :integer          not null, primary key
#  amount       :float
#  date         :datetime
#  operation_id :integer
#  account_id   :integer
#  created_at   :datetime
#  updated_at   :datetime
#

class SimulatedAccountOperation < ActiveRecord::Base
  belongs_to :account
  belongs_to :operation

  def name
    "Simulated #{operation.name}"
  end
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_filter :init_accounts
  before_filter :frequencies_for_select, only: [:show]

  def show
    init_account(params[:id])
    @default_simulation_date = Date.today.end_of_month
    @operation = Operation.new(account_id: @account.id)
  end

  def update
    @account = Account.find(params[:id])

     if @account.update(params.require(:account).permit([:name, :sold]))
      @account.update(sold_date: DateTime.now)
    end
    respond_to :js
  end

  def sold_at
    @account = Account.find(params[:id])
    @simulation_date = params[:simulation][:date].present? ? Date.parse(params[:simulation][:date]) : Date.today
    @simulated_sold = @simulation_date.present? ? @account.sold_at(@simulation_date) : nil
    respond_to :js
  end

  def new
    @new_account = Account.new(sold: 0, sold_date: Date.today)
  end

  def create
    @account = Account.create(params.require(:account).permit(:name, :description, :sold).merge(sold_date: Date.today))
    if @account.errors.blank?
      redirect_to account_path(@account)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include ApplicationHelper
  include AccountsHelper

  protect_from_forgery with: :exception
end

app/controllers/operations_controller.rb
class OperationsController < ApplicationController
  include AccountsHelper
  before_filter :frequencies_for_select, only: [:edit]

  def create
    @status = {}

    if params[:operation][:amount].present?
      operation_type = params[:operation][:amount].to_i < 0 ? 'outcomes' : 'incomes'
      params[:operation][:is_recurrent] = params[:operation][:frequency].present?
      @account = Account.find(params[:operation][:account_id])
      @operation = @account.send(operation_type).new(permitted_params)

      if @operation.save
        @status[:success] = "Operation enregistree"
        @operations = @account.operations
        @new_operation = Operation.new
        init_account(@account.id)
      else
        @status[:errors] = @operation.errors.messages.map{|k,v| k.to_s.downcase}
      end
    else
      @status[:errors] = ['amount']
    end

    respond_to :js
  end

  def edit
    @operation = Operation.find(params[:id])
    respond_to :js
  end

  def update
    @operation = Operation.find(params[:id])
    if @operation.update(permitted_params)
      init_account(@operation.account_id)
    end
    respond_to :js
  end

  def destroy
    @operation = Operation.find(params[:id])
    account_id = @operation.account_id
    @operation.destroy
    init_account(account_id)
    respond_to :js
  end

  private

  def permitted_params
    params.require(:operation).permit(:account_id, :amount, :name, :description, :date, :date_from, :date_to, :is_recurrent, :frequency)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  before_filter :init_accounts

  def index
  end
end

app/helpers/accounts_helper.rb
module AccountsHelper

  def init_account(id)
    @account = Account.find(id)
    @operations = @account.operations.order(amount: :desc, date: :asc)
    @new_operation = Operation.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def init_accounts
    @accounts = Account.all
  end

  def frequencies_for_select
    @frequencies_for_select = Operation::FREQUENCIES.map { |f| [I18n.t("frequency.#{f}").titlecase, f] }
  end
end

app/views/accounts/_sold_at.haml
- if @simulated_sold
  .row
    .col-md-12.card.white.text-center.simulation-header
      .card-inner
        %label= "Solde le #{@simulation_date}"
        .simulated-sold= "#{number_with_precision(@simulated_sold, locale: :fr, precision: 2)}€"
  .row
    .col-md-12.card.white
      .card-inner
        %table.table.table-condensed.table-hover
          %tbody
            - @account.simulated_account_operations.each do |simulated_operation|
              %tr
                %th.col-md-2= simulated_operation.operation.name
                %td.col-md-4= simulated_operation.operation.description
                %td.col-md-1
                  %div{ class: "#{simulated_operation.operation.is_income? ? 'success' : 'danger' } pull-right right-padded" }
                    %strong= "#{number_with_precision(simulated_operation.operation.amount, locale: :fr, precision: 2)}€"
                %td.col-md-3= simulated_operation.date.strftime('%d/%m/%Y')
                %td
                  - if simulated_operation.operation.is_recurrent?
                    = I18n.t("frequency.#{simulated_operation.operation.frequency}").upcase
                  - else
                    PONCTUELLE
                %td

app/views/accounts/new.haml
.row
  .col-md-12.card.white.condensed
    .card-inner
      .row
        .col-md-3
        .col-md-6.text-center
          %h1 Créer un compte
        .col-md-3
= form_for(@new_account, class: 'form-inline') do |f|
  .row
    .col-md-12.card.white.condensed
      .card-inner
        .row
          .col-md-3
          .col-md-6.text-center
            %label.light-label Nom du compte
            = f.text_field :name, class: 'form-control very-light invisible-border'
          .col-md-3
  .row
    .col-md-12.card.white.condensed
      .card-inner
        .row
          .col-md-3
          .col-md-6.text-center
            %label.light-label Description
            = f.text_field :description, class: 'form-control very-light invisible-border'
          .col-md-3
  .row
    .col-md-12.card.white.condensed
      .card-inner
        .row
          .col-md-3
          .col-md-6.text-center
            %label.light-label
              Solde le
              %span#account-sold-date= @new_account.sold_date.strftime('%d/%m/%Y')
            = f.text_field :sold, class: 'form-control very-light invisible-border'
          .col-md-3
  .row
    .col-md-12.card.white.condensed
      .card-inner
        .row
          .col-md-12
            %button.btn.btn-success.fluid{:type => "submit"} CREER

app/views/accounts/show.haml
.row
  .col-md-12.card.white
    .card-inner
      %i#account-form-status.glyphicon.glyphicon-ok.success
      = form_for(@account, remote: true, class: 'form-inline', id: 'edit-account-form') do |f|
        .row
          .col-md-6.text-center
            %label.light-label Nom du compte
            = f.text_field :name, class: 'form-control invisible-border', placeholder: 'Nom'
          .col-md-6.text-center
            %label.light-label
              Solde le
              %span#account-sold-date= I18n.l(@account.sold_date)
            = f.text_field :sold, class: 'form-control invisible-border', placeholder: 'Solde courrant'
.row
  .col-md-12.card.title
    .card-inner
      Opérations
      %a#add-operation.btn.btn-xs.btn-success.pull-right.rounded{"data-target" => "#add-operation-modal", "data-toggle" => "modal", :role => "button", :tabindex => "0"}
        %i.glyphicon.glyphicon-plus
.row
  .col-md-12.card.white
    .card-inner
      #operations
        = render 'operations/table'

.row
  .col-md-12.card.title
    .card-inner
      Simulation
      = form_tag(:sold_at_account, url: sold_at_account_path(@account), method: :post, remote: true, class: 'form-inline pull-right', id: 'simulation-form') do
        .form-group
          .input-group
            = text_field_tag 'simulation[date]', I18n.l(@default_simulation_date), class: 'form-control datepicker invisible-border', placeholder: 'Date'
            %span.input-group-btn
              %button.btn.btn-success{:type => "submit"} LANCER
#simulation-results
= render 'operations/new_modal'

app/views/accounts/sold_at.js.erb
$('#simulation-results').html('<%= escape_javascript(render :partial => "accounts/sold_at") %>');

app/views/accounts/update.js.erb
$('#account-form-status').removeClass('warning').addClass('success');
$('#account-sold-date').html("<%= @account.sold_date.strftime('%d/%m/%Y') %>")

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MY BUDGET</title>
  <link href='https://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'shared/main_nav', simulation: true %>
  <%= yield %>
</div>

</body>
</html>

app/views/operations/_edit_modal.haml
#edit-operation-modal.modal.fade{:role => "dialog", :tabindex => "-1"}
  .modal-dialog.modal-lg{:role => "document"}
    .modal-content
      = form_for(@operation, remote: true) do |f|
        .modal-header
          %button.close{"aria-label" => "Close", "data-dismiss" => "modal", :type => "button"}
            %span{"aria-hidden" => "true"} ×
          %h4.modal-title= "OPERATION: #{f.object.name}"
        .modal-body
          = render 'operations/form_fields', f: f
        .modal-footer
          %button.btn.btn-success{:type => "submit"} SAUVEGARDER
          %button.btn.btn-default{"data-dismiss" => "modal", :type => "button"} FERMER

app/views/operations/_form_fields.haml
= f.hidden_field :account_id
.form-group= f.text_field :name, class: 'form-control invisible-border', placeholder: 'Nom'
.form-group= f.text_field :description, class: 'form-control invisible-border', placeholder: 'Description'
.form-group= f.text_field :amount, class: 'form-control invisible-border', placeholder: 'Montant'
.form-group= f.text_field :date, class: 'form-control invisible-border datepicker', placeholder: 'Date'
.form-group= f.text_field :date_from, class: 'form-control invisible-border datepicker', placeholder: 'Du'
.form-group= f.text_field :date_to, class: 'form-control invisible-border datepicker', placeholder: 'Au'
.form-group= f.select(:frequency, options_for_select(@frequencies_for_select, f.object.frequency), {}, { class: 'select2 fluid' })

app/views/operations/_new_modal.haml
#add-operation-modal.modal.fade{:role => "dialog", :tabindex => "-1"}
  .modal-dialog.modal-lg{:role => "document"}
    .modal-content
      = form_for(@operation, method: :post, url: operations_path, remote: true) do |f|
        .modal-header
          %button.close{"aria-label" => "Close", "data-dismiss" => "modal", :type => "button"}
            %span{"aria-hidden" => "true"} ×
          %h4.modal-title OPERATION
        .modal-body
          = render 'operations/form_fields', f: f
        .modal-footer
          %button.btn.btn-success{:type => "submit"} CREER
          %button.btn.btn-default{"data-dismiss" => "modal", :type => "button"} FERMER

app/views/operations/_table.haml
.row
  .col-md-6.text-center
    %label.light-label Incomes
    %ul
      - Operation::FREQUENCIES.each do |frequency|
        - amount = @account.incomes_amount(frequency)
        - if amount
          %li
            = "#{I18n.t('frequency.' + frequency)}: "
            %span.success= amount
  .col-md-6.text-center
    %label.light-label Outcomes
    %ul
      - Operation::FREQUENCIES.each do |frequency|
        - amount = @account.outcomes_amount(frequency)
        - if amount
          %li
            = "#{I18n.t('frequency.' + frequency)}: "
            %span.danger= amount
%br/
%table.table.table-condensed.table-hover
  %thead
    %tr
      %th Name
      %th Description
      %th Income
      %th Outcome
      %th Date
      %th From Date
      %th To Date
      %th Frequency
      %th Manage
  %tbody
    - @operations.each do |operation|
      %tr
        %th= operation.name
        %td= operation.description
        %td
          - if operation.is_income?
            %strong.success.pull-right.right-padded= "#{number_with_precision(operation.amount, locale: :fr, precision: 2)}€"
        %td
          - if operation.is_outcome?
            %strong.danger.pull-right.right-padded= "#{number_with_precision(operation.amount, locale: :fr, precision: 2)}€"
        %td= I18n.l(operation.date.to_date)
        %td= I18n.l(operation.date_from.to_date) if operation.date_from
        %td= I18n.l(operation.date_to.to_date) if operation.date_to
        %td= I18n.t("frequency.#{operation.frequency}").upcase
        %td
          = form_for(operation, method: :delete, remote: true, html: { class: 'pull-right' }) do |f|
            %button.btn.btn-danger.btn-xs.rounded{ type: 'submit' }
              %i.glyphicon.glyphicon-trash
          = form_tag(edit_operation_path(operation), method: :get, remote: true, html: { class: 'pull-right' }) do
            %button.btn.btn-primary.btn-xs.rounded{ type: 'submit' }
              %i.glyphicon.glyphicon-edit
#edit-operation-modal-container

app/views/operations/create.js.erb
$('.errored').removeClass('errored');
<% if @status[:success] %>
  $('#operations').html('<%= escape_javascript(render :partial => "operations/table") %>')
  refreshOperationsTable();
<% else %>
  <% @status[:errors].each do |errored_field| %>
    $("#operation_<%= errored_field %>").addClass('errored');
  <% end %>
<% end %>

app/views/operations/destroy.js.erb
$('#operations').html('<%= escape_javascript(render :partial => "operations/table") %>')
refreshOperationsTable();

app/views/operations/edit.js.erb
$('#edit-operation-modal-container').html('<%= escape_javascript(render :partial => "operations/edit_modal") %>');
$('#edit-operation-modal').modal('show');
$('.select2').select2();

app/views/operations/update.js.erb
$('#edit-operation-modal').modal('hide');
setTimeout(function() {
  $('#edit-operation-modal-container').html('');
  $('#operations').html('<%= escape_javascript(render :partial => "operations/table") %>')
  refreshOperationsTable();
}, 500);

app/views/shared/_main_nav.haml
%nav#header.navbar.navbar-default
  .container-fluid
    .navbar-header
      %button.navbar-toggle.collapsed{"aria-expanded" => "false", "data-target" => "#navbar-collapse", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      - if defined?(@account)
        = link_to @account.name.upcase, account_path(@account), class: 'navbar-brand'
      - else
        = link_to 'MY BUDGET', root_path, class: 'navbar-brand'

    #navbar-collapse.collapse.navbar-collapse
      %ul.nav.navbar-nav.navbar-right
        %li.dropdown
          %a.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :href => "#", :role => "button"}
            MES COMPTES
            %span.caret
          %ul.dropdown-menu
            - @accounts.each do |account|
              %li.account
                = link_to account.name, account_path(account)
            %li.account
              = link_to 'Créer un compte', new_account_path